import type { Property } from "./types";

const properties: Property[] = [
  {
    id: 1,
    title: "Luxury Waterfront Villa in Banana Island",
    category: "villa",
    price: "120,000,000",
    location: "Banana Island, Lagos",
    image: "/re/listing_card_1.png",
    featured: true,
    features: { bedrooms: 6, bathrooms: 7, area: "850 sqm" },
  },
  {
    id: 2,
    title: "Modern Penthouse in Lekki Phase 1",
    category: "penthouse",
    price: "45,000,000",
    location: "Lekki Phase 1, Lagos",
    image: "/re/listing_card_2.png",
    featured: true,
    features: { bedrooms: 4, bathrooms: 4, area: "320 sqm" },
  },
  {
    id: 3,
    title: "Contemporary Mansion in Ikoyi",
    category: "mansion",
    price: "85,000,000",
    location: "Ikoyi, Lagos",
    image: "/re/listing_card_3.png",
    featured: true,
    features: { bedrooms: 5, bathrooms: 6, area: "600 sqm" },
  },
  // More properties in Lagos
  {
    id: 16,
    title: "Family Villa in Ajah",
    category: "villa",
    price: "3,800,000",
    location: "Ajah, Lagos",
    image: "/re/listing_card_4.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "210 sqm" },
  },
  {
    id: 17,
    title: "Executive Penthouse in Victoria Island",
    category: "penthouse",
    price: "110,000,000",
    location: "Victoria Island, Lagos",
    image: "/re/listing_card_5.png",
    featured: true,
    features: { bedrooms: 4, bathrooms: 4, area: "300 sqm" },
  },
  {
    id: 18,
    title: "Modern Villa in Surulere",
    category: "villa",
    price: "25,000,000",
    location: "Surulere, Lagos",
    image: "/re/listing_card_6.png",
    featured: false,
    features: { bedrooms: 4, bathrooms: 4, area: "350 sqm" },
  },
  {
    id: 19,
    title: "Luxury Apartment in Ikeja",
    category: "apartment",
    price: "15,000,000",
    location: "Ikeja, Lagos",
    image: "/re/listing_card_1.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 2, area: "250 sqm" },
  },

  // Properties in Abuja
  {
    id: 20,
    title: "Penthouse with City View in Maitama",
    category: "penthouse",
    price: "60,000,000",
    location: "Maitama, Abuja",
    image: "/re/listing_card_2.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "280 sqm" },
  },
  {
    id: 21,
    title: "Mansion in Asokoro",
    category: "mansion",
    price: "102,000,000",
    location: "Asokoro, Abuja",
    image: "/re/listing_card_3.png",
    featured: true,
    features: { bedrooms: 5, bathrooms: 5, area: "600 sqm" },
  },
  {
    id: 22,
    title: "Modern Villa in Garki",
    category: "villa",
    price: "40,000,000",
    location: "Garki, Abuja",
    image: "/re/listing_card_4.png",
    featured: false,
    features: { bedrooms: 4, bathrooms: 4, area: "320 sqm" },
  },
  {
    id: 23,
    title: "Luxury Apartment in Wuse",
    category: "apartment",
    price: "9,000,000",
    location: "Wuse, Abuja",
    image: "/re/listing_card_5.png",
    featured: true,
    features: { bedrooms: 2, bathrooms: 2, area: "180 sqm" },
  },

  // Properties in Port Harcourt
  {
    id: 24,
    title: "Beachfront Villa in Port Harcourt",
    category: "villa",
    price: "35,000,000",
    location: "Port Harcourt, Rivers",
    image: "/re/listing_card_1.png",
    featured: true,
    features: { bedrooms: 4, bathrooms: 4, area: "400 sqm" },
  },
  {
    id: 25,
    title: "Penthouse with Lagoon View",
    category: "penthouse",
    price: "48,000,000",
    location: "GRA, Port Harcourt",
    image: "/re/listing_card_2.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "290 sqm" },
  },
  {
    id: 26,
    title: "Executive Mansion in Trans Amadi",
    category: "mansion",
    price: "95,000,000",
    location: "Trans Amadi, Port Harcourt",
    image: "/re/listing_card_3.png",
    featured: true,
    features: { bedrooms: 5, bathrooms: 6, area: "600 sqm" },
  },
  {
    id: 27,
    title: "Modern Apartment in Rumuola",
    category: "apartment",
    price: "12,000,000",
    location: "Rumuola, Port Harcourt",
    image: "/re/listing_card_4.png",
    featured: false,
    features: { bedrooms: 2, bathrooms: 2, area: "150 sqm" },
  },
];

export default properties;
