import type { Property } from "./types";

const properties: Property[] = [
  {
    id: 1,
    title: "Luxury Waterfront Villa in Banana Island",
    category: "villa",
    price: "2,500,000,000",
    location: "Banana Island, Lagos",
    image: "/re/listing_card_1.png",
    featured: true,
    features: { bedrooms: 6, bathrooms: 7, area: "850 sqm" },
  },
  {
    id: 2,
    title: "Modern Penthouse in Lekki Phase 1",
    category: "penthouse",
    price: "450,000,000",
    location: "Lekki Phase 1, Lagos",
    image: "/re/listing_card_2.png",
    featured: true,
    features: { bedrooms: 4, bathrooms: 4, area: "320 sqm" },
  },
  {
    id: 3,
    title: "Contemporary Mansion in Ikoyi",
    category: "mansion",
    price: "1,200,000,000",
    location: "Ikoyi, Lagos",
    image: "/re/listing_card_3.png",
    featured: true,
    features: { bedrooms: 5, bathrooms: 6, area: "600 sqm" },
  },
  {
    id: 4,
    title: "Family Villa in Ajah",
    category: "villa",
    price: "180,000,000",
    location: "Ajah, Lagos",
    image: "/re/listing_card_4.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "210 sqm" },
  },
  {
    id: 5,
    title: "Luxury Penthouse in Victoria Island",
    category: "penthouse",
    price: "650,000,000",
    location: "Victoria Island, Lagos",
    image: "/re/listing_card_5.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "280 sqm" },
  },
  {
    id: 6,
    title: "Modern Villa in Surulere",
    category: "villa",
    price: "220,000,000",
    location: "Surulere, Lagos",
    image: "/re/listing_card_6.png",
    featured: false,
    features: { bedrooms: 4, bathrooms: 4, area: "350 sqm" },
  },
  {
    id: 7,
    title: "Executive Mansion in Ikeja GRA",
    category: "mansion",
    price: "900,000,000",
    location: "Ikeja GRA, Lagos",
    image: "/re/listing_card_6.png",
    featured: true,
    features: { bedrooms: 6, bathrooms: 7, area: "720 sqm" },
  },

  // **New Entries**
  {
    id: 8,
    title: "Beachfront Villa in Port Harcourt",
    category: "villa",
    price: "350,000,000",
    location: "Port Harcourt, Rivers",
    image: "/re/listing_card_1.png",
    featured: true,
    features: { bedrooms: 4, bathrooms: 4, area: "400 sqm" },
  },
  {
    id: 9,
    title: "Penthouse with City View in Abuja",
    category: "penthouse",
    price: "550,000,000",
    location: "Maitama, Abuja",
    image: "/re/listing_card_2.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "280 sqm" },
  },
  {
    id: 10,
    title: "Mansion in Kano GRA",
    category: "mansion",
    price: "1,100,000,000",
    location: "Kano GRA, Kano",
    image: "/re/listing_card_3.png",
    featured: false,
    features: { bedrooms: 5, bathrooms: 5, area: "650 sqm" },
  },
  {
    id: 11,
    title: "Luxury Apartment in Ibadan",
    category: "apartment",
    price: "120,000,000",
    location: "Ring Road, Ibadan",
    image: "/re/listing_card_4.png",
    featured: true,
    features: { bedrooms: 2, bathrooms: 2, area: "120 sqm" },
  },
  {
    id: 12,
    title: "Villa in Owerri",
    category: "villa",
    price: "280,000,000",
    location: "Owerri, Imo",
    image: "/re/listing_card_5.png",
    featured: false,
    features: { bedrooms: 3, bathrooms: 3, area: "320 sqm" },
  },
  {
    id: 13,
    title: "Penthouse in Uyo",
    category: "penthouse",
    price: "480,000,000",
    location: "Uyo, Akwa Ibom",
    image: "/re/listing_card_6.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "290 sqm" },
  },
  {
    id: 14,
    title: "Mansion in Calabar",
    category: "mansion",
    price: "950,000,000",
    location: "Calabar, Cross River",
    image: "/re/listing_card_1.png",
    featured: true,
    features: { bedrooms: 6, bathrooms: 6, area: "700 sqm" },
  },
  {
    id: 15,
    title: "Apartment in Abuja Central",
    category: "apartment",
    price: "150,000,000",
    location: "Central Area, Abuja",
    image: "/re/listing_card_2.png",
    featured: false,
    features: { bedrooms: 2, bathrooms: 2, area: "130 sqm" },
  },
  {
    id: 16,
    title: "Family Villa in Ajah",
    category: "villa",
    price: "180,000,000",
    location: "Ajah, Lagos",
    image: "/re/listing_card_4.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "210 sqm" },
  },
  {
    id: 17,
    title: "Executive Penthouse in Victoria Island",
    category: "penthouse",
    price: "750,000,000",
    location: "Victoria Island, Lagos",
    image: "/re/listing_card_5.png",
    featured: true,
    features: { bedrooms: 4, bathrooms: 4, area: "300 sqm" },
  },
  {
    id: 18,
    title: "Modern Villa in Surulere",
    category: "villa",
    price: "220,000,000",
    location: "Surulere, Lagos",
    image: "/re/listing_card_6.png",
    featured: false,
    features: { bedrooms: 4, bathrooms: 4, area: "350 sqm" },
  },
  {
    id: 19,
    title: "Luxury Apartment in Ikeja",
    category: "apartment",
    price: "200,000,000",
    location: "Ikeja, Lagos",
    image: "/re/listing_card_1.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 2, area: "250 sqm" },
  },

  // Properties in Abuja
  {
    id: 20,
    title: "Penthouse with City View in Maitama",
    category: "penthouse",
    price: "550,000,000",
    location: "Maitama, Abuja",
    image: "/re/listing_card_2.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "280 sqm" },
  },
  {
    id: 21,
    title: "Mansion in Asokoro",
    category: "mansion",
    price: "1,000,000,000",
    location: "Asokoro, Abuja",
    image: "/re/listing_card_3.png",
    featured: true,
    features: { bedrooms: 5, bathrooms: 5, area: "600 sqm" },
  },
  {
    id: 22,
    title: "Modern Villa in Garki",
    category: "villa",
    price: "380,000,000",
    location: "Garki, Abuja",
    image: "/re/listing_card_4.png",
    featured: false,
    features: { bedrooms: 4, bathrooms: 4, area: "320 sqm" },
  },
  {
    id: 23,
    title: "Luxury Apartment in Wuse",
    category: "apartment",
    price: "150,000,000",
    location: "Wuse, Abuja",
    image: "/re/listing_card_5.png",
    featured: true,
    features: { bedrooms: 2, bathrooms: 2, area: "180 sqm" },
  },

  // Properties in Port Harcourt
  {
    id: 24,
    title: "Beachfront Villa in Port Harcourt",
    category: "villa",
    price: "350,000,000",
    location: "Port Harcourt, Rivers",
    image: "/re/listing_card_1.png",
    featured: true,
    features: { bedrooms: 4, bathrooms: 4, area: "400 sqm" },
  },
  {
    id: 25,
    title: "Penthouse with Lagoon View",
    category: "penthouse",
    price: "480,000,000",
    location: "GRA, Port Harcourt",
    image: "/re/listing_card_2.png",
    featured: true,
    features: { bedrooms: 3, bathrooms: 3, area: "290 sqm" },
  },
  {
    id: 26,
    title: "Executive Mansion in Trans Amadi",
    category: "mansion",
    price: "900,000,000",
    location: "Trans Amadi, Port Harcourt",
    image: "/re/listing_card_3.png",
    featured: true,
    features: { bedrooms: 5, bathrooms: 6, area: "600 sqm" },
  },
  {
    id: 27,
    title: "Modern Apartment in Rumuola",
    category: "apartment",
    price: "160,000,000",
    location: "Rumuola, Port Harcourt",
    image: "/re/listing_card_4.png",
    featured: false,
    features: { bedrooms: 2, bathrooms: 2, area: "150 sqm" },
  },
];

export default properties;
